kind: Deployment
apiVersion: apps/v1
metadata:
  name: ioc-v1
  namespace: ioc-dev
  labels:
    app: ioc
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ioc
      version: v1
  template:
    metadata:
      labels:
        app: ioc
        pod-template-hash: 5bf9d659bd
        version: v1
    spec:
      volumes:
        - name: volume-e6gjit
          configMap:
            name: ioc
            defaultMode: 420
        - name: volume-h5d4nm
          configMap:
            name: ioc
            defaultMode: 420
        - name: volume-ghj0uv
          persistentVolumeClaim:
            claimName: ioc-gs
        - name: volume-5pc19b
          configMap:
            name: ioc
            defaultMode: 420
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-4a0aqz
          configMap:
            name: ioc
            defaultMode: 420
      containers:
        - name: container-c3qlrd
          image: '$HARBOR_URL$IMAGE_TAG'
          ports:
            - name: tcp-80
              containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
          resources: {}
          volumeMounts:
            - name: volume-e6gjit
              readOnly: true
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: volume-h5d4nm
              readOnly: true
              mountPath: /usr/share/nginx/html/static/config/config.js
              subPath: config.js
            - name: volume-ghj0uv
              mountPath: /usr/share/nginx/html/static/tiles/
            - name: volume-5pc19b
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-4a0aqz
              readOnly: true
              mountPath: /usr/share/nginx/html/static/config/qiankun.js
              subPath: qiankun.js
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      securityContext: {}
      imagePullSecrets:
        - name: harbor
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
